/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.Summary;
import EstructurasDeDatos.Lista;
import EstructurasDeDatos.Nodo;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author fabriziospiotta
 */
public class InterfazInicial extends javax.swing.JFrame {
    
    private static Lista summaryList;
    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazInicial() {
        this.summaryList = new Lista();
        initComponents();
    }
        
    /**
     * Función que carga, lee y procesa el archivo txt que el usuario selecciono
     * @return un String ya separado con todo el texto almacenado dentro del txt
     */
    public String leerArchivo(){
        JFileChooser archivo = new JFileChooser();
        archivo.showOpenDialog(archivo);
        File file = archivo.getSelectedFile();
        if (!file.toString().contains("txt")) {
            JOptionPane.showMessageDialog(null, "EL ARCHIVO SELECCIONADO NO ES TXT");
            return null;
        } else {
            String line;
            String texto = "";

            try { 
                if (!file.exists()){
                    file.createNewFile();
                } else {               
                    FileReader fr = new FileReader(file);
                    BufferedReader br = new BufferedReader(fr);

                    while((line = br.readLine()) != null){
                        if (!line.isEmpty()) {
                            texto += line + "\n";
                        }    
                    }

                    if (!"".equals(texto)) {
                        String [] textoSeparadoAutores = texto.split("Autores\n");
                        String [] nombreArticuloArray = textoSeparadoAutores[0].split("\n");
                        String nombreArticulo = nombreArticuloArray[0];
                        String [] textoSeparadoResumen = textoSeparadoAutores[1].split("Resumen\n");
                        String [] autoresArray = textoSeparadoResumen[0].split("\n");
                        Lista autoresList = new Lista();
                        for (int i = 0; i < autoresArray.length; i++) {
                            autoresList.AppendAtTheEnd(autoresArray[i]);
                        }
                        String [] textoSeparadoKeyWords = textoSeparadoResumen[1].split(".\n");
                        String cuerpoResumen = textoSeparadoKeyWords[0] + ".";
                        String [] textoSeparadoDosPuntos = textoSeparadoKeyWords[1].split(": ");
                        String [] keyWordsArray = textoSeparadoDosPuntos[1].split(", ");
                        Lista keyWordsList = new Lista();
                        for (int i = 0; i < keyWordsArray.length; i++) {
                            keyWordsList.AppendAtTheEnd(keyWordsArray[i]);
                        }

                        Summary newSummary = new Summary(nombreArticulo, autoresList, cuerpoResumen, keyWordsList);
                        
                        boolean encontrado = false;
                        if (!this.summaryList.isEmpty()) {
                            Nodo<Summary> aux = this.summaryList.getpFirst();
                            for (int i = 0; i < summaryList.getSize(); i++) {
                                if (aux.getElemento().getTitulo().equalsIgnoreCase(nombreArticulo)) {
                                    encontrado = true;
                                }
                                aux = aux.getpNext();
                            }
                        }
                        if (encontrado == false) {
                                this.summaryList.AppendAtTheEnd(newSummary);
                                JOptionPane.showMessageDialog(null, "LECTURA COMPLETADA");
                        } else {
                            JOptionPane.showMessageDialog(null, "EL resumen ya esta registrado");
                        }
                    }
                    br.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "NO SELECCIONO NINGUN ARCHIVO O NO SE PUDO LEER PROPORCIONADO");
            }  return texto;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CargarArticulosButton = new javax.swing.JButton();
        IrMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        CargarArticulosButton.setText("CARGAR ARTICULOS");
        CargarArticulosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArticulosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CargarArticulosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        IrMenuButton.setText("IR AL MENU");
        IrMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(IrMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarArticulosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArticulosButtonActionPerformed
        // TODO add your handling code here:
        this.leerArchivo();
    }//GEN-LAST:event_CargarArticulosButtonActionPerformed

    private void IrMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrMenuButtonActionPerformed
        // TODO add your handling code here:
        InterfazMenu menu = new InterfazMenu(summaryList);
        this.setVisible(false);
        menu.setVisible(true);
                    
    }//GEN-LAST:event_IrMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarArticulosButton;
    private javax.swing.JButton IrMenuButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
